name: ci
on:
  push:
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Workspace sync
        run: go work sync

      # Lint + tests por módulo
      - name: Vet server
        run: go -C server vet ./...
      - name: Test server
        run: go -C server test ./... -v

      - name: Vet cli
        run: go -C clients/cli vet ./...

      # Builds
      - name: Build server
        run: go -C server build -o ../bin/server ./cmd/server
      - name: Build cli
        run: go -C clients/cli build -o ../../bin/cli .

      # Smoke del CLI (no tests propios)
      - name: CLI --help
        run: ./bin/cli --help
