name: release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Build CLI and Server (matrix)
        run: |
          set -euo pipefail
          mkdir -p dist
          platforms=(
            linux/amd64
            linux/arm64
            windows/amd64
            darwin/amd64
            darwin/arm64
          )
          for p in "${platforms[@]}"; do
            GOOS="${p%/*}"; GOARCH="${p#*/}"
            ext=""; [ "$GOOS" = windows ] && ext=.exe
            # server
            echo "Building server for $GOOS/$GOARCH"
            (cd server && env CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o ../dist/server-${GOOS}-${GOARCH}${ext} ./cmd/server)
            # cli
            echo "Building cli for $GOOS/$GOARCH"
            (cd clients/cli && env CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o ../../dist/clip-sync-${GOOS}-${GOARCH}${ext} .)
          done

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

